import Notebook from "../models/Notebook.js";
import PlantTemplate from "../models/PlantTemplate.js";
import Guide from "../models/Guide.js";
import { AppError } from "../utils/AppError.js";

/**
 * Service xử lý tích hợp Notebook với PlantTemplate
 */

// Lấy template phù hợp với notebook (dựa trên guide's plant_group)
export const getTemplateForNotebook = async (notebookId) => {
  const notebook = await Notebook.findById(notebookId).populate("guide_id");

  if (!notebook) {
    throw new AppError("Không tìm thấy nhật ký", 404);
  }

  // Nếu đã có template_id, trả về template đó
  if (notebook.template_id) {
    const template = await PlantTemplate.findById(notebook.template_id);
    return template;
  }

  // Nếu chưa có template, tìm template active phù hợp với plant_group của guide
  if (notebook.guide_id && notebook.guide_id.plant_group) {
    const template = await PlantTemplate.findOne({
      plant_group: notebook.guide_id.plant_group,
      is_active: true,
    }).sort({ usage_count: -1 });

    return template;
  }

  return null;
};

// Gán template cho notebook
export const assignTemplateToNotebook = async (notebookId, templateId) => {
  const notebook = await Notebook.findById(notebookId);
  const template = await PlantTemplate.findById(templateId);

  if (!notebook) {
    throw new AppError("Không tìm thấy nhật ký", 404);
  }

  if (!template) {
    throw new AppError("Không tìm thấy template", 404);
  }

  notebook.template_id = templateId;

  // Khởi tạo stages_tracking
  notebook.stages_tracking = template.stages.map((stage, index) => ({
    stage_number: index + 1,
    stage_name: stage.name, // ← FIX: Dùng 'name' từ PlantTemplate schema
    started_at: index === 0 ? notebook.planted_date : null,
    is_current: index === 0,
  }));

  notebook.current_stage = 1;

  // ✅ Tính progress dựa trên các stage đã hoàn thành (stage 1 chưa hoàn thành = 0%) (now async)
  await notebook.updateProgress(template.stages);

  await notebook.save();

  // Tăng usage_count của template
  template.usage_count += 1;
  await template.save();

  // Generate daily checklist cho stage đầu tiên
  await generateDailyChecklist(notebookId);

  return notebook;
};

// Tính stage hiện tại dựa trên số ngày đã trồng
export const calculateCurrentStage = async (notebookId) => {
  const notebook = await Notebook.findById(notebookId).populate("template_id");

  if (!notebook || !notebook.template_id) {
    return null;
  }

  const template = notebook.template_id;
  const daysPlanted = notebook.current_day;

  // Tìm stage tương ứng với số ngày đã trồng
  const stageInfo = template.getStageByDay(daysPlanted);

  if (stageInfo && stageInfo.stage_number !== notebook.current_stage) {
    // Cập nhật stage mới
    await updateCurrentStage(notebookId, stageInfo.stage_number);
  }

  return stageInfo;
};

// Cập nhật stage hiện tại
export const updateCurrentStage = async (notebookId, newStageNumber) => {
  const notebook = await Notebook.findById(notebookId).populate("template_id");

  if (!notebook || !notebook.template_id) {
    throw new AppError("Không tìm thấy nhật ký hoặc template", 404);
  }

  const template = notebook.template_id;

  if (newStageNumber > template.stages.length) {
    throw new AppError("Số stage không hợp lệ", 400);
  }

  // Hoàn thành stage cũ
  const oldStageIndex = notebook.stages_tracking.findIndex(
    (s) => s.stage_number === notebook.current_stage
  );
  if (oldStageIndex !== -1) {
    notebook.stages_tracking[oldStageIndex].is_current = false;
    notebook.stages_tracking[oldStageIndex].completed_at = new Date();
  }

  // Bắt đầu stage mới
  const newStageIndex = notebook.stages_tracking.findIndex(
    (s) => s.stage_number === newStageNumber
  );
  if (newStageIndex !== -1) {
    notebook.stages_tracking[newStageIndex].is_current = true;
    notebook.stages_tracking[newStageIndex].started_at = new Date();
  }

  notebook.current_stage = newStageNumber;

  // ✅ Update progress: chỉ tính các stage đã completed (now async)
  await notebook.updateProgress(template.stages);

  await notebook.save();

  // Generate lại checklist cho stage mới
  await generateDailyChecklist(notebookId);

  return notebook;
};

// Tạo daily checklist từ template's autogenerated_tasks
export const generateDailyChecklist = async (notebookId) => {
  const notebook = await Notebook.findById(notebookId).populate("template_id");

  if (!notebook || !notebook.template_id) {
    return null;
  }

  const template = notebook.template_id;
  const currentStage = template.stages.find(
    (s, index) => index + 1 === notebook.current_stage
  );

  if (!currentStage) {
    return null;
  }

  const today = new Date();
  today.setHours(0, 0, 0, 0);

  // Kiểm tra nếu đã generate hôm nay
  if (
    notebook.last_checklist_generated &&
    notebook.last_checklist_generated.setHours(0, 0, 0, 0) === today.getTime()
  ) {
    return notebook.daily_checklist;
  }

  // Lọc tasks theo frequency (nếu task là daily hoặc đến ngày thực hiện)
  const daysInStage =
    Math.floor(notebook.current_day) - currentStage.start_day + 1;

  const newChecklist = currentStage.autogenerated_tasks
    .filter((task) => {
      if (task.frequency === "daily") return true;
      if (task.frequency === "every_2_days") return daysInStage % 2 === 0;
      if (task.frequency === "every_3_days") return daysInStage % 3 === 0;
      if (task.frequency === "weekly") return daysInStage % 7 === 0;
      return false;
    })
    .map((task) => ({
      task_name: task.task_name,
      description: task.description,
      priority: task.priority,
      frequency: task.frequency,
      is_completed: false,
    }));

  notebook.daily_checklist = newChecklist;
  notebook.last_checklist_generated = today;
  await notebook.save();

  return newChecklist;
};

// Đánh dấu hoàn thành task trong checklist
export const completeChecklistTask = async (notebookId, taskName) => {
  const notebook = await Notebook.findById(notebookId).populate("template_id");

  if (!notebook) {
    throw new AppError("Không tìm thấy nhật ký", 404);
  }

  const task = notebook.daily_checklist.find((t) => t.task_name === taskName);

  if (!task) {
    throw new AppError("Không tìm thấy công việc", 404);
  }

  // Toggle logic: nếu đã hoàn thành thì chuyển về chưa hoàn thành, và ngược lại
  task.is_completed = !task.is_completed;
  task.completed_at = task.is_completed ? new Date() : null;

  // Track task completion trong stage_tracking
  const currentStageTracking = notebook.stages_tracking.find(
    (s) => s.stage_number === notebook.current_stage
  );

  if (currentStageTracking) {
    if (task.is_completed) {
      // Thêm vào completed_tasks nếu chưa có
      const alreadyCompleted = currentStageTracking.completed_tasks?.some(
        (t) => t.task_name === taskName
      );

      if (!alreadyCompleted) {
        if (!currentStageTracking.completed_tasks) {
          currentStageTracking.completed_tasks = [];
        }
        currentStageTracking.completed_tasks.push({
          task_name: taskName,
          completed_at: new Date(),
        });
      }
    } else {
      // Xóa khỏi completed_tasks nếu uncheck
      if (currentStageTracking.completed_tasks) {
        currentStageTracking.completed_tasks =
          currentStageTracking.completed_tasks.filter(
            (t) => t.task_name !== taskName
          );
      }
    }
  }

  // ✅ Update progress: tính cả stage hiện tại (now async)
  if (notebook.template_id && notebook.template_id.stages) {
    await notebook.updateProgress(notebook.template_id.stages);
    console.log(`📊 Progress updated: ${notebook.progress}%`);
    console.log(
      `📋 Completed tasks in current stage: ${
        currentStageTracking?.completed_tasks?.length || 0
      }`
    );
  }

  // ✅ Cập nhật daily_progress cho ngày hôm nay
  if (currentStageTracking) {
    const today = new Date().toISOString().split("T")[0]; // YYYY-MM-DD

    console.log(
      `🔍 Checking daily_logs for stage ${notebook.current_stage} on ${today}`
    );

    // Tìm hoặc tạo daily_log cho ngày hôm nay
    let dailyLog = currentStageTracking.daily_logs?.find(
      (log) => log.date?.toISOString().split("T")[0] === today
    );

    if (!dailyLog) {
      if (!currentStageTracking.daily_logs) {
        currentStageTracking.daily_logs = [];
      }
      dailyLog = {
        date: new Date(),
        daily_progress: 0,
      };
      currentStageTracking.daily_logs.push(dailyLog);
      console.log(`➕ Created new daily_log for ${today}`);
    } else {
      console.log(
        `✅ Found existing daily_log for ${today}: ${dailyLog.daily_progress}%`
      );
    }

    // Tính daily_progress dựa trên tasks của ngày hôm nay
    const todayTasks = notebook.daily_checklist || [];
    const completedTodayTasks = todayTasks.filter((t) => t.is_completed).length;
    const totalTodayTasks = todayTasks.length;

    if (totalTodayTasks > 0) {
      dailyLog.daily_progress = Math.round(
        (completedTodayTasks / totalTodayTasks) * 100
      );
      console.log(
        `📅 Daily progress for ${today}: ${dailyLog.daily_progress}% (${completedTodayTasks}/${totalTodayTasks})`
      );
    }
  } else {
    console.warn(
      `⚠️ No currentStageTracking found for stage ${notebook.current_stage}`
    );
  }

  // ✅ Kiểm tra xem stage hiện tại đã hoàn thành 100% chưa
  // Nếu có, mark stage as completed và tự động chuyển sang stage tiếp theo
  if (currentStageTracking && notebook.template_id) {
    const stageCompletion = await notebook.getCurrentStageCompletion();
    console.log(`🎯 Current stage completion: ${stageCompletion}%`);

    if (stageCompletion >= 100 && !currentStageTracking.completed_at) {
      // Mark stage as completed
      currentStageTracking.completed_at = new Date();
      console.log(`✅ Stage ${notebook.current_stage} marked as COMPLETED`);

      // Cập nhật lại plant progress
      await notebook.updateProgress(notebook.template_id.stages);
      console.log(`🌱 Plant progress updated: ${notebook.progress}%`);

      // TODO: Tự động chuyển sang stage tiếp theo (nếu có)
      // const nextStageNumber = notebook.current_stage + 1;
      // if (nextStageNumber <= notebook.template_id.stages.length) {
      //   await updateCurrentStage(notebookId, nextStageNumber);
      // }
    }
  }

  await notebook.save();

  return notebook;
};

// Lấy tất cả observations của stage hiện tại
export const getCurrentStageObservations = async (notebookId) => {
  const notebook = await Notebook.findById(notebookId).populate("template_id");

  if (!notebook || !notebook.template_id) {
    return [];
  }

  const template = notebook.template_id;
  const currentStage = template.stages.find(
    (s, index) => index + 1 === notebook.current_stage
  );

  return currentStage ? currentStage.observations : [];
};

// Cập nhật observation cho stage hiện tại
export const updateStageObservation = async (
  notebookId,
  observationKey,
  value
) => {
  const notebook = await Notebook.findById(notebookId);

  if (!notebook) {
    throw new AppError("Không tìm thấy nhật ký", 404);
  }

  const stageTracking = notebook.stages_tracking.find(
    (s) => s.stage_number === notebook.current_stage
  );

  if (!stageTracking) {
    throw new AppError("Không tìm thấy stage tracking", 404);
  }

  // Tìm hoặc tạo mới observation
  const existingObs = stageTracking.observations.find(
    (o) => o.key === observationKey
  );

  if (existingObs) {
    existingObs.value = value;
    existingObs.observed_at = new Date();
  } else {
    stageTracking.observations.push({
      key: observationKey,
      value: value,
      observed_at: new Date(),
    });
  }

  await notebook.save();
  return notebook;
};

// Kiểm tra xem có nên tự động chuyển stage không (dựa trên rules)
export const checkAutoStageTransition = async (notebookId) => {
  const notebook = await Notebook.findById(notebookId).populate("template_id");

  if (!notebook || !notebook.template_id) {
    return false;
  }

  const template = notebook.template_id;
  const currentStageTracking = notebook.stages_tracking.find(
    (s) => s.stage_number === notebook.current_stage
  );

  if (!currentStageTracking) {
    return false;
  }

  // Kiểm tra rules: auto_skip_stages
  if (template.rules && template.rules.auto_skip_stages) {
    for (const skipRule of template.rules.auto_skip_stages) {
      // Nếu có observation match với điều kiện skip
      const matchedObs = currentStageTracking.observations.find(
        (o) => o.key === skipRule.observation_key && o.value === true
      );

      if (matchedObs && skipRule.skip_to_stage) {
        // Auto chuyển sang stage chỉ định
        await updateCurrentStage(notebookId, skipRule.skip_to_stage);
        return true;
      }
    }
  }

  return false;
};

// Lấy timeline cho notebook (tất cả stages với thời gian)
export const getNotebookTimeline = async (notebookId) => {
  // Validate notebookId
  if (!notebookId || notebookId === "undefined" || notebookId === "null") {
    throw new AppError("Invalid notebook ID", 400);
  }

  const notebook = await Notebook.findById(notebookId).populate("template_id");

  if (!notebook || !notebook.template_id) {
    return null;
  }

  const template = notebook.template_id;

  const timeline = notebook.stages_tracking.map((tracking) => {
    const templateStage = template.stages.find(
      (s, idx) => idx + 1 === tracking.stage_number
    );

    return {
      stage_number: tracking.stage_number,
      stage_name: tracking.stage_name,
      started_at: tracking.started_at,
      completed_at: tracking.completed_at,
      is_current: tracking.is_current,
      duration_days: templateStage
        ? templateStage.day_end - templateStage.day_start + 1
        : null,
      start_day: templateStage ? templateStage.day_start : null,
      end_day: templateStage ? templateStage.day_end : null,
      observations: tracking.observations,
    };
  });

  return {
    planted_date: notebook.planted_date,
    current_day: notebook.current_day,
    progress: notebook.progress,
    total_days: template.total_days,
    timeline,
  };
};
