import mongoose from "mongoose";
import PlantTemplate from "../models/PlantTemplate.js";
import { connectDB } from "../config/db.js";
import "dotenv/config";

const checkTemplates = async () => {
  try {
    await connectDB();
    console.log("✅ Connected to MongoDB");

    const templates = await PlantTemplate.find({});

    console.log(`\n📋 Found ${templates.length} templates:\n`);

    templates.forEach((template) => {
      console.log(`\n🌱 Template: ${template.template_name}`);
      console.log(`   Plant Group: ${template.plant_group}`);
      console.log(`   Stages: ${template.stages.length}`);

      template.stages.forEach((stage, index) => {
        console.log(`\n   Stage ${index + 1}: ${stage.name}`);
        console.log(`   - Days: ${stage.day_start} - ${stage.day_end}`);
        console.log(`   - Tasks: ${stage.autogenerated_tasks?.length || 0}`);

        if (stage.autogenerated_tasks && stage.autogenerated_tasks.length > 0) {
          stage.autogenerated_tasks.forEach((task) => {
            console.log(`     ✓ ${task.task_name} (${task.frequency})`);
          });
        } else {
          console.log(`     ⚠️ NO TASKS DEFINED`);
        }
      });
    });

    await mongoose.connection.close();
    console.log("\n✅ Done");
  } catch (error) {
    console.error("❌ Error:", error);
    process.exit(1);
  }
};

checkTemplates();
