import "dotenv/config";
import mongoose from "mongoose";
import PlantTemplate from "../models/PlantTemplate.js";
import User from "../models/User.js";

const templates = [
  {
    template_name: "Rau ăn lá cơ bản",
    plant_group: "leaf_vegetable",
    group_description:
      "Template cho các loại rau ăn lá như xà lách, rau muống, cải xanh có chu kỳ ngắn 30-45 ngày",
    plant_examples: [
      "Xà lách",
      "Rau muống",
      "Cải xanh",
      "Rau dền",
      "Cải bó xôi",
    ],
    stages: [
      {
        stage_number: 1,
        name: "Nảy mầm",
        description: "Hạt nảy mầm, mầm vươn lên khỏi đất",
        day_start: 1,
        day_end: 7,
        stage_image:
          "https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=400",
        autogenerated_tasks: [
          {
            task_name: "Giữ ẩm đất",
            description: "Phun sương 2 lần/ngày sáng và chiều để giữ ẩm",
            frequency: "daily",
            priority: "high",
          },
          {
            task_name: "Kiểm tra nhiệt độ",
            description: "Đảm bảo nhiệt độ 20-25°C",
            frequency: "daily",
            priority: "medium",
          },
        ],
        observation_required: [
          {
            key: "has_sprout",
            label: "Đã nảy mầm?",
            description: "Mầm cao khoảng 1-2cm, có 2 lá mầm",
          },
        ],
      },
      {
        stage_number: 2,
        name: "Ra lá thật",
        description: "Lá thật đầu tiên xuất hiện",
        day_start: 8,
        day_end: 14,
        stage_image:
          "https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?w=400",
        autogenerated_tasks: [
          {
            task_name: "Tưới nước",
            description: "Tưới 1 lần/ngày vào buổi sáng",
            frequency: "daily",
            priority: "high",
          },
          {
            task_name: "Kiểm tra sâu bệnh",
            description: "Quan sát lá có bị sâu ăn không",
            frequency: "every_2_days",
            priority: "medium",
          },
        ],
        observation_required: [
          {
            key: "has_true_leaf",
            label: "Đã có lá thật?",
            description: "2-3 lá thật đầu tiên, khác với lá mầm",
          },
        ],
      },
      {
        stage_number: 3,
        name: "Sinh trưởng mạnh",
        description: "Cây phát triển nhanh, tăng chiều cao và số lá",
        day_start: 15,
        day_end: 30,
        stage_image:
          "https://images.unsplash.com/photo-1592495989226-03f88104f8cc?w=400",
        autogenerated_tasks: [
          {
            task_name: "Tưới nước",
            description: "Tưới đều đặn hằng ngày",
            frequency: "daily",
            priority: "high",
          },
          {
            task_name: "Bón phân",
            description: "Bón phân hữu cơ loãng",
            frequency: "weekly",
            priority: "medium",
          },
          {
            task_name: "Tỉa lá già",
            description: "Cắt bỏ lá già phía dưới",
            frequency: "weekly",
            priority: "low",
          },
        ],
        observation_required: [
          {
            key: "strong_growth",
            label: "Cây phát triển khỏe?",
            description: "Nhiều lá xanh tốt, thân cây chắc khỏe",
          },
        ],
      },
      {
        stage_number: 4,
        name: "Thu hoạch",
        description: "Cây đã trưởng thành, sẵn sàng thu hoạch",
        day_start: 31,
        day_end: 45,
        stage_image:
          "https://images.unsplash.com/photo-1622383563227-04401ab4e5ea?w=400",
        autogenerated_tasks: [
          {
            task_name: "Thu hoạch",
            description: "Cắt lá từ ngoài vào trong",
            frequency: "every_2_days",
            priority: "high",
          },
          {
            task_name: "Vệ sinh chậu",
            description: "Dọn dẹp lá úa, rác",
            frequency: "every_3_days",
            priority: "low",
          },
        ],
        observation_required: [
          {
            key: "ready_harvest",
            label: "Sẵn sàng thu hoạch?",
            description: "Lá đủ lớn, xanh tốt, không bị sâu bệnh",
          },
        ],
      },
    ],
    rules: {
      safe_delay_days: 3,
      auto_skip: true,
      warning_days: 1,
    },
    status: "active",
  },
  {
    template_name: "Cây củ ngắn ngày",
    plant_group: "root_vegetable",
    group_description:
      "Template cho củ cải, cà rốt baby và các loại củ ngắn ngày 45-60 ngày",
    plant_examples: ["Củ cải trắng", "Cà rốt baby", "Củ dền"],
    stages: [
      {
        stage_number: 1,
        name: "Nảy mầm",
        description: "Hạt nảy mầm",
        day_start: 1,
        day_end: 10,
        stage_image:
          "https://images.unsplash.com/photo-1589923188900-85dae523342b?w=400",
        autogenerated_tasks: [
          {
            task_name: "Giữ ẩm",
            description: "Phun sương đều đặn",
            frequency: "daily",
            priority: "high",
          },
        ],
        observation_required: [
          {
            key: "has_sprout",
            label: "Đã nảy mầm?",
            description: "Mầm xuất hiện",
          },
        ],
      },
      {
        stage_number: 2,
        name: "Ra lá, bắt đầu phát triển củ",
        description: "Lá phát triển, củ bắt đầu hình thành",
        day_start: 11,
        day_end: 25,
        stage_image:
          "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400",
        autogenerated_tasks: [
          {
            task_name: "Tưới nước",
            description: "Tưới đều, không để úng",
            frequency: "daily",
            priority: "high",
          },
          {
            task_name: "Xới đất nhẹ",
            description: "Xới đất xung quanh gốc",
            frequency: "weekly",
            priority: "medium",
          },
        ],
        observation_required: [
          {
            key: "root_forming",
            label: "Củ bắt đầu phồng?",
            description: "Thấy củ nhô lên khỏi mặt đất",
          },
        ],
      },
      {
        stage_number: 3,
        name: "Củ phát triển",
        description: "Củ phát triển nhanh",
        day_start: 26,
        day_end: 50,
        stage_image:
          "https://images.unsplash.com/photo-1447175008436-054170c2e979?w=400",
        autogenerated_tasks: [
          {
            task_name: "Tưới nước đều",
            description: "Tưới đúng lượng để củ không bị nứt",
            frequency: "daily",
            priority: "high",
          },
          {
            task_name: "Bón phân lân kali",
            description: "Bổ sung dinh dưỡng cho củ",
            frequency: "weekly",
            priority: "medium",
          },
        ],
        observation_required: [
          {
            key: "root_growing",
            label: "Củ đang phát triển tốt?",
            description: "Củ to dần, không bị dị dạng",
          },
        ],
      },
      {
        stage_number: 4,
        name: "Thu hoạch",
        description: "Củ đã trưởng thành",
        day_start: 51,
        day_end: 60,
        stage_image:
          "https://images.unsplash.com/photo-1522184216316-3c25379f9760?w=400",
        autogenerated_tasks: [
          {
            task_name: "Nhổ củ",
            description: "Nhổ nhẹ nhàng, không làm gãy",
            frequency: "daily",
            priority: "high",
          },
        ],
        observation_required: [
          {
            key: "ready_harvest",
            label: "Đủ kích thước?",
            description: "Củ đủ to, màu sắc đẹp",
          },
        ],
      },
    ],
    rules: {
      safe_delay_days: 5,
      auto_skip: true,
      warning_days: 2,
    },
    status: "active",
  },
  {
    template_name: "Rau quả ngắn ngày",
    plant_group: "fruit_short_term",
    group_description:
      "Template cho dưa leo, cà chua bi, ớt và các loại quả ngắn ngày 60-90 ngày",
    plant_examples: ["Dưa leo", "Cà chua bi", "Ớt chuông", "Dưa chuột"],
    stages: [
      {
        stage_number: 1,
        name: "Nảy mầm",
        description: "Hạt nảy mầm",
        day_start: 1,
        day_end: 10,
        stage_image:
          "https://images.unsplash.com/photo-1592831746760-85c0a40b19f8?w=400",
        autogenerated_tasks: [
          {
            task_name: "Giữ ẩm",
            description: "Phun sương 2-3 lần/ngày",
            frequency: "daily",
            priority: "high",
          },
        ],
        observation_required: [
          {
            key: "has_sprout",
            label: "Đã nảy mầm?",
            description: "Mầm xuất hiện",
          },
        ],
      },
      {
        stage_number: 2,
        name: "Sinh trưởng sinh dưỡng",
        description: "Cây phát triển thân lá",
        day_start: 11,
        day_end: 30,
        stage_image:
          "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=400",
        autogenerated_tasks: [
          {
            task_name: "Tưới nước",
            description: "Tưới đều đặn sáng chiều",
            frequency: "daily",
            priority: "high",
          },
          {
            task_name: "Bón phân đạm",
            description: "Bón phân cho cây phát triển",
            frequency: "weekly",
            priority: "medium",
          },
          {
            task_name: "Dựng giàn",
            description: "Dựng cọc cho cây leo",
            frequency: "weekly",
            priority: "medium",
          },
        ],
        observation_required: [
          {
            key: "strong_plant",
            label: "Cây đã khỏe?",
            description: "Thân chắc, nhiều lá",
          },
        ],
      },
      {
        stage_number: 3,
        name: "Ra hoa, đậu quả",
        description: "Cây ra hoa và bắt đầu đậu quả",
        day_start: 31,
        day_end: 60,
        stage_image:
          "https://images.unsplash.com/photo-1595855759920-86582396756e?w=400",
        autogenerated_tasks: [
          {
            task_name: "Tưới nước đều",
            description: "Tưới buổi sáng, tránh úng",
            frequency: "daily",
            priority: "high",
          },
          {
            task_name: "Bón phân lân kali",
            description: "Bón phân cho quả",
            frequency: "weekly",
            priority: "high",
          },
          {
            task_name: "Thụ phấn thủ công",
            description: "Dùng붓 bông thụ phấn nếu cần",
            frequency: "every_2_days",
            priority: "medium",
          },
        ],
        observation_required: [
          {
            key: "has_flower",
            label: "Đã ra hoa?",
            description: "Có hoa nở",
          },
          {
            key: "has_fruit",
            label: "Đã đậu quả?",
            description: "Thấy quả nhỏ hình thành",
          },
        ],
      },
      {
        stage_number: 4,
        name: "Quả phát triển và thu hoạch",
        description: "Quả lớn dần và thu hoạch",
        day_start: 61,
        day_end: 90,
        stage_image:
          "https://images.unsplash.com/photo-1592924357892-91fb0178b2c6?w=400",
        autogenerated_tasks: [
          {
            task_name: "Tưới nước",
            description: "Tưới đều để quả không bị nứt",
            frequency: "daily",
            priority: "high",
          },
          {
            task_name: "Thu hoạch quả chín",
            description: "Hái quả khi chín vừa",
            frequency: "every_2_days",
            priority: "high",
          },
        ],
        observation_required: [
          {
            key: "fruit_ripe",
            label: "Quả đã chín?",
            description: "Màu sắc đẹp, kích thước phù hợp",
          },
        ],
      },
    ],
    rules: {
      safe_delay_days: 4,
      auto_skip: true,
      warning_days: 2,
    },
    status: "active",
  },
];

async function seedPlantTemplates() {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGODB_CONNECTIONSTRING);
    console.log("✅ Connected to MongoDB");

    // Find an expert user to assign as creator
    let expertUser = await User.findOne({ role: "expert" });

    if (!expertUser) {
      // If no expert exists, find admin or create a dummy expert
      expertUser = await User.findOne({ role: "admin" });

      if (!expertUser) {
        console.log("⚠️  No expert or admin found. Creating dummy expert...");
        const bcrypt = await import("bcrypt");
        const hashedPassword = await bcrypt.hash("Expert@123", 10);

        expertUser = await User.create({
          username: "expert_system",
          email: "expert@farmhub.com",
          password: hashedPassword,
          role: "expert",
          isVerified: true,
        });
        console.log("✅ Created dummy expert user");
      }
    }

    console.log(`📝 Using user: ${expertUser.username} (${expertUser.role})`);

    // Clear existing templates
    const deleteResult = await PlantTemplate.deleteMany({});
    console.log(`🗑️  Deleted ${deleteResult.deletedCount} existing templates`);

    // Insert new templates
    const templatesWithCreator = templates.map((template) => ({
      ...template,
      created_by: expertUser._id,
    }));

    const result = await PlantTemplate.insertMany(templatesWithCreator);
    console.log(`✅ Created ${result.length} plant templates`);

    // Display summary
    console.log("\n📊 Summary:");
    result.forEach((template, index) => {
      console.log(`\n${index + 1}. ${template.template_name}`);
      console.log(`   Group: ${template.plant_group}`);
      console.log(`   Stages: ${template.stages.length}`);
      console.log(
        `   Total days: ${Math.max(...template.stages.map((s) => s.day_end))}`
      );
      console.log(`   Examples: ${template.plant_examples.join(", ")}`);
    });

    console.log("\n✅ Seed data created successfully!");
    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding data:", error);
    process.exit(1);
  }
}

seedPlantTemplates();
