import mongoose from "mongoose";

// Schema cho một task tự động sinh
const AutoGeneratedTaskSchema = new mongoose.Schema(
  {
    task_name: {
      type: String,
      required: true,
    },
    description: {
      type: String,
      default: "",
    },
    frequency: {
      type: String,
      enum: ["daily", "every_2_days", "every_3_days", "weekly"],
      default: "daily",
    },
    illustration_image: {
      type: String, // URL hoặc path
      default: null,
    },
    priority: {
      type: String,
      enum: ["low", "medium", "high"],
      default: "medium",
    },
  },
  { _id: false }
);

// Schema cho điều kiện quan sát
const ObservationSchema = new mongoose.Schema(
  {
    key: {
      type: String,
      required: true, // ví dụ: "has_sprout", "has_true_leaf"
    },
    label: {
      type: String,
      required: true, // ví dụ: "Đã nảy mầm?", "Đã có lá thật?"
    },
    description: {
      type: String,
      default: "",
    },
  },
  { _id: false }
);

// Schema cho mỗi giai đoạn (Stage)
const StageSchema = new mongoose.Schema(
  {
    stage_number: {
      type: Number,
      required: true,
    },
    name: {
      type: String,
      required: true, // ví dụ: "Nảy mầm", "Ra lá thật"
    },
    description: {
      type: String,
      default: "",
    },
    day_start: {
      type: Number,
      required: true,
    },
    day_end: {
      type: Number,
      required: true,
    },
    weight: {
      type: Number,
      default: 25, // Trọng số % của stage (tổng các stage = 100%)
      min: 0,
      max: 100,
    },
    stage_image: {
      type: String, // URL hoặc path đến ảnh mẫu lý tưởng
      default: null,
    },
    // Checklist mặc định được hệ thống sinh ra
    autogenerated_tasks: [AutoGeneratedTaskSchema],
    // Các điều kiện quan sát nhị phân
    observation_required: [ObservationSchema],
  },
  { _id: false }
);

// Schema chính PlantTemplate
const PlantTemplateSchema = new mongoose.Schema(
  {
    // Tên template (để phân biệt)
    template_name: {
      type: String,
      required: true,
      unique: true,
    },
    // Nhóm cây (plant_group)
    plant_group: {
      type: String,
      required: true,
      enum: [
        "leaf_vegetable", // Rau ăn lá
        "root_vegetable", // Cây củ
        "fruit_short_term", // Rau/quả ngắn ngày
        "fruit_long_term", // Cây ăn quả dài ngày
        "bean_family", // Họ đậu ngắn ngày
        "herb", // Cây gia vị
        "flower_vegetable", // Rau ăn hoa
        "other", // Khác
      ],
      index: true,
    },
    // Mô tả về nhóm cây này
    group_description: {
      type: String,
      default: "",
    },
    // Danh sách ví dụ cây thuộc nhóm (để mapping)
    plant_examples: {
      type: [String],
      default: [],
    },
    // Các giai đoạn phát triển (3-5 stages)
    stages: {
      type: [StageSchema],
      validate: {
        validator: function (stages) {
          return stages && stages.length >= 3 && stages.length <= 6;
        },
        message: "Template phải có từ 3 đến 6 giai đoạn",
      },
    },
    // Rules xử lý chậm trễ
    rules: {
      safe_delay_days: {
        type: Number,
        default: 3, // Cho phép trễ 3 ngày
      },
      auto_skip: {
        type: Boolean,
        default: true, // Tự động skip stage nếu quá trễ
      },
      warning_days: {
        type: Number,
        default: 1, // Cảnh báo khi trễ 1 ngày
      },
    },
    // Trạng thái template
    status: {
      type: String,
      enum: ["draft", "active", "archived"],
      default: "draft",
    },
    // Người tạo (expert)
    created_by: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    // Metadata
    version: {
      type: Number,
      default: 1,
    },
    notes: {
      type: String,
      default: "",
    },
    // Thống kê sử dụng
    usage_count: {
      type: Number,
      default: 0,
    },
  },
  {
    timestamps: true, // Tự động tạo createdAt và updatedAt
  }
);

// Indexes
PlantTemplateSchema.index({ plant_group: 1, status: 1 });
PlantTemplateSchema.index({ created_by: 1 });
PlantTemplateSchema.index({ template_name: "text" });

// Virtual field: Tổng số ngày của template
PlantTemplateSchema.virtual("total_days").get(function () {
  if (!this.stages || this.stages.length === 0) return 0;
  return Math.max(...this.stages.map((s) => s.day_end));
});

// Method: Lấy stage theo số ngày
PlantTemplateSchema.methods.getStageByDay = function (dayNumber) {
  return this.stages.find(
    (stage) => dayNumber >= stage.day_start && dayNumber <= stage.day_end
  );
};

// Method: Lấy stage tiếp theo
PlantTemplateSchema.methods.getNextStage = function (currentStageNumber) {
  return this.stages.find(
    (stage) => stage.stage_number === currentStageNumber + 1
  );
};

// Static method: Tìm template theo plant_group
PlantTemplateSchema.statics.findByPlantGroup = function (plantGroup) {
  return this.find({ plant_group: plantGroup, status: "active" });
};

const PlantTemplate = mongoose.model("PlantTemplate", PlantTemplateSchema);

export default PlantTemplate;
